TITLE = "The Legend of Shifu"
PATH_ICON = "assets/icon/icon.png"
WIN_WIDTH = 800
WIN_HEIGHT = 600
SCALE = 2
SPRITESIZE = 32
PATH_LEVEL1 = "assets/game/levels/level1.lua"
COLLISION_MODE = "bump"
PATH_SHIFU = "assets/sprites/shifu.png"
OBJECT_PLAYER = "player"