ENABLE_DEBUG = false
TITLE = "The Legend of Shifu"
PATH_ICON = "assets/icon/icon.png"
FONT_SIZE = 18
WIN_WIDTH = 800
WIN_HEIGHT = 600
SCALE = 2
SPRITESIZE = 32
COLLISION_MODE = "bump"
PATH_LEVEL1 = "assets/game/levels/level1.lua"
PATH_SHIFU = "assets/sprites/shifu.png"
PATH_PLAYER_HIT_SOUND = "assets/sounds/262313__steffcaffrey__cat-meow2.wav"
OBJECT_PLAYER = "player"
PLAYER_SPEED = 110
PATH_PEE = "assets/sprites/pee.png"
BULLET_TIMER = 0.4
BULLET_SPEED = 250
BULLET_WIDTH = 2
BULLET_HEIGHT = 8
PATH_BULLET_SOUND = "assets/sounds/56271__q-k__water-gulp.wav"
PATH_SKELETON = "assets/sprites/skeleton.png"
PATH_SKELETON_HIT_SOUND = "assets/sounds/163447__under7dude__zombie-hit.wav"
HITTED_SPEED = 5
DIFFICULTY = 1.5 --0.5 easy 1 medium 1.5 hard