ENABLE_DEBUG = false
TITLE = "The Legend of Shifu"
PATH_ICON = "assets/icon/icon.png"
WIN_WIDTH = 800
WIN_HEIGHT = 600
SCALE = 2
SPRITESIZE = 32
COLLISION_MODE = "bump"
PATH_LEVEL1 = "assets/game/levels/level1.lua"
PATH_SHIFU = "assets/sprites/shifu.png"
OBJECT_PLAYER = "player"
PLAYER_SPEED = 110
PATH_PEE = "assets/sprites/pee.png"
BULLET_TIMER = 0.4
BULLET_SPEED = 250
BULLET_WIDTH = 2
BULLET_HEIGHT = 8